version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 25
    versioning-strategy: increase
    allow:
      - dependency0name: "tgrid"